---
# Pass in a comma-separated list of repos to use (e.g. "remi,epel").
php_enablerepo: ""
# List of php packages to install
php_packages:
  - php5
  - php5-suhosin
  - php5-xmlrpc
  - libapache2-mod-php5
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php-apc
  - php-soap
  - php-pear

# Various php.ini settings.
php_memory_limit: "256M"
php_max_execution_time: "60"
php_upload_max_filesize: "64M"
php_apc_enabled_in_ini: true
php_apc_cache_by_default: "1"
php_apc_shm_size: "96M"
php_date_timezone: "America/New_York"

# Location of php configuration files.
php_conf_path: /etc/php5/apache2
php_cli_conf_path: /etc/php5/cli
php_extension_conf_path: /etc/php5/conf.d
#php_extension_conf_path: /etc/php5/mods-available
php_apc_conf_filename: apc.ini

# Whether to use mod_php
php_enable_webserver: true
php_webserver_daemon: "apache2"

# Whether to use fpm (untested)
php_enable_php_fpm: false

php_sendmail_path: "/usr/sbin/sendmail -t -i"

php_error_log: "syslog"
php_allow_url_fopen: true

# xdebug params
php_enable_xdebug: true
php_xdebug_remote_enable: "true"
php_xdebug_remote_connect_back: "true"
php_xdebug_remote_host: localhost
php_xdebug_remote_port: "9000"
php_xdebug_remote_log: /tmp/xdebug.log
php_xdebug_idekey: ECLIPSE_DBGP

# whether to enable mysql support
php_enable_mysql: true

